# Generated by Django 4.0.3 on 2022-03-14 18:20

from django.db import migrations

def add_grade_levels(apps, schema_editor):
    Grade = apps.get_model('timetable', 'Grade')
    for i in range(1, 6):
        Grade.objects.create(level=i)
        
def reverse_operation(apps, scheme_editor):
    Grade = apps.get_model('timetable', 'Grade')
    Grade.objects.all().delete()

        
class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_grade_levels, reverse_operation)
    ]
