# Generated by Django 4.0.3 on 2022-03-14 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('instructors', models.ManyToManyField(related_name='subjects', to='timetable.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
